AWSTemplateFormatVersion: 2010-09-09
Resources:
  EC2AutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      VPCZoneIdentifier: !Split 
        - ','
        - !Ref VPCSubnets
      LaunchTemplate:
        LaunchTemplateId: !Ref EC2LaunchTemplate
        Version: !GetAtt 
          - EC2LaunchTemplate
          - LatestVersionNumber
      MinSize: 1
      MaxSize: 5
      DesiredCapacity: 2
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300
      MetricsCollection:
        - Granularity: 1Minute
  KeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: my-key-pair
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
  PublicRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref VPCSubnets
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: my-security-group
      GroupDescription: A security group for my EC2 instances
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  VPCSubnets:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      CidrBlock: 10.0.0.0/24
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties: {}
  InternetGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
  PublicRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable
  EC2LaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: my-launch-template
      LaunchTemplateData:
        ImageId: ami-0b5eea76982371e91
        InstanceType: t3.micro
        KeyName: my-key-pair
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: true
            DeleteOnTermination: true
            Groups:
              - !Ref SecurityGroup
  CloudWatchAlarmHigh:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: my-high-cpu-alarm
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Period: 60
      Threshold: 75
      Statistic: Average
      AlarmActions:
        - !Ref ScaleUpPolicy
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref EC2AutoScalingGroup
  CloudWatchAlarmLow:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: my-low-cpu-alarm
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 1
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Period: 60
      Threshold: 30
      Statistic: Average
      AlarmActions:
        - !Ref ScaleDownPolicy
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref EC2AutoScalingGroup
  ScaleUpPolicy:
    Type: 'AWS::AutoScaling::ScalingPolicy'
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref EC2AutoScalingGroup
      Cooldown: 300
      ScalingAdjustment: 1
  ScaleDownPolicy:
    Type: 'AWS::AutoScaling::ScalingPolicy'
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref EC2AutoScalingGroup
      Cooldown: 300
      ScalingAdjustment: -1
Metadata:
  'AWS::CloudFormation::Designer':
    65c5dbfa-05c4-4f33-8608-41d4817c89c9:
      size:
        width: 60
        height: 60
      position:
        x: 380
        'y': 120
      z: 1
      embeds: []
    0babdcbd-a721-4bb0-b1ec-16a6c38f3af7:
      size:
        width: 400
        height: 290
      position:
        x: -80
        'y': 10
      z: 1
      embeds:
        - ca270342-6f8b-4434-b068-adfc7489f1c4
        - 8ae74d03-41f6-4d2d-901b-4b321176e35e
    96d95b83-d8dd-478c-aae2-2aa9e9968169:
      size:
        width: 240
        height: 240
      position:
        x: 500
        'y': 90
      z: 1
      embeds:
        - 7b8cc94b-f545-4742-aca8-45fbb0a0daa8
    7b8cc94b-f545-4742-aca8-45fbb0a0daa8:
      size:
        width: 60
        height: 60
      position:
        x: 520
        'y': 120
      z: 2
      parent: 96d95b83-d8dd-478c-aae2-2aa9e9968169
      embeds: []
      isassociatedwith:
        - 65c5dbfa-05c4-4f33-8608-41d4817c89c9
      iscontainedinside:
        - 96d95b83-d8dd-478c-aae2-2aa9e9968169
    9d93483a-de93-4050-b516-b08e30d644c5:
      source:
        id: 0babdcbd-a721-4bb0-b1ec-16a6c38f3af7
      target:
        id: 65c5dbfa-05c4-4f33-8608-41d4817c89c9
    8ae74d03-41f6-4d2d-901b-4b321176e35e:
      size:
        width: 240
        height: 240
      position:
        x: 40
        'y': 40
      z: 2
      parent: 0babdcbd-a721-4bb0-b1ec-16a6c38f3af7
      embeds:
        - 37236ea6-c9e4-4d91-afb2-ce5c630766e7
    ca270342-6f8b-4434-b068-adfc7489f1c4:
      size:
        width: 60
        height: 60
      position:
        x: -60
        'y': 100
      z: 2
      parent: 0babdcbd-a721-4bb0-b1ec-16a6c38f3af7
      embeds: []
      iscontainedinside:
        - 0babdcbd-a721-4bb0-b1ec-16a6c38f3af7
    e8e2648b-c9bc-44ae-9650-e97d270a17ae:
      size:
        width: 60
        height: 60
      position:
        x: -10
        'y': 330
      z: 1
      embeds: []
    29de5dfe-4152-4995-9b85-8c9e9dddd776:
      size:
        width: 60
        height: 60
      position:
        x: 380
        'y': 220
      z: 1
      embeds: []
    37236ea6-c9e4-4d91-afb2-ce5c630766e7:
      size:
        width: 60
        height: 60
      position:
        x: 70
        'y': 100
      z: 3
      parent: 8ae74d03-41f6-4d2d-901b-4b321176e35e
      embeds: []
      iscontainedinside:
        - 8ae74d03-41f6-4d2d-901b-4b321176e35e
    c824c76f-e382-4fb3-8282-87019d8cdb77:
      size:
        width: 60
        height: 60
      position:
        x: 350
        'y': 0
      z: 1
      embeds: []
    6748bb5c-033b-4180-ac32-ab912819fe33:
      size:
        width: 60
        height: 60
      position:
        x: 450
        'y': 0
      z: 1
      embeds: []
    e9dbf675-6c74-41a7-9476-e206c7975297:
      size:
        width: 60
        height: 60
      position:
        x: 340
        'y': -90
      z: 1
      embeds: []
    d9408766-ab61-453e-83e9-e0265e529892:
      size:
        width: 60
        height: 60
      position:
        x: 460
        'y': -90
      z: 1
      embeds: []
